import Head from "next/head";
import Image from "next/image";
import Box from "@mui/material/Box";
import Board from "../components/Board";

export default function Home() {
    const data = {
        "2022-03-01": ["Test 01", "Date 01"],
        "2022-03-02": ["Test 02"],
    };
    let data2 = [
      "2022-03-01",
      "2022-03-02",
      "2022-03-03",
      "2022-03-04",
      "2022-03-05",
      "2022-03-06",
      "2022-03-07",
      "2022-03-08",
      "2022-03-09",
    ]
    return (
        <>
            <Head>
                <title>Event Page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Box sx={{ height: "100vh", display: "flex", padding: "10px" }}>
                {data2.map((item) => (
                    <Board item={item} />
                ))}
            </Box>
        </>
    );
}
